version: "3.7"

services:
  app:
    build: .
    depends_on:
      - db
  db:
    image: "postgres:13"
    ports:
      - "5432:5432"
    volumes:
      - ./dbscripts/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./dbscripts/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER:  "energy"
      POSTGRES_PASSWORD: "samplepassword"
